class Settings:
    DISK_USAGE_THRESHOLD = 90
    MEMORY_USAGE_THRESHOLD = 85
    CPU_USAGE_THRESHOLD = 90
    DUMMY_DISK_USAGE = True
    MONITORING_PERIOD_IN_SECONDS = 0.25
    PLOT_PERIOD_IN_SECONDS = 1
